# Generated by Django 4.1.2 on 2022-11-15 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duck_image', models.ImageField(upload_to='photos')),
                ('duck_first_name', models.CharField(max_length=30)),
                ('duck_last_name', models.CharField(max_length=30)),
                ('duck_age', models.IntegerField(default=0)),
                ('duck_birthday', models.DateField(default=datetime.date.today)),
                ('body_color', models.CharField(max_length=30)),
                ('beak_color', models.CharField(max_length=30)),
                ('owner_first_name', models.CharField(max_length=30)),
                ('owner_last_name', models.CharField(max_length=30)),
            ],
        ),
    ]
