# Generated by Django 4.1.2 on 2022-12-03 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duckdatabase', '0003_remove_duck_owner_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='duck',
            table='Duck',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Owner',
        ),
    ]
