# Generated by Django 4.1.2 on 2022-12-03 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duckdatabase', '0004_alter_duck_table_alter_owner_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Color',
            },
        ),
        migrations.AlterField(
            model_name='duck',
            name='beak_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beak_color', to='duckdatabase.color'),
        ),
        migrations.AlterField(
            model_name='duck',
            name='body_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_color', to='duckdatabase.color'),
        ),
    ]
