# Generated by Django 4.1.2 on 2022-12-09 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duckdatabase', '0005_color_alter_duck_beak_color_alter_duck_body_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duck',
            name='beak_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_beak_color', to='duckdatabase.color'),
        ),
        migrations.AlterField(
            model_name='duck',
            name='body_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_body_color', to='duckdatabase.color'),
        ),
        migrations.AlterField(
            model_name='duck',
            name='duck_image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
