# Generated by Django 4.1.2 on 2022-12-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckdatabase', '0007_remove_duck_duck_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='duck',
            name='duck_description',
            field=models.TextField(blank=True),
        ),
    ]
